In [1]:
# 데이터 로드
import pandas as pd

df = pd.read_csv("supply_chain_data.csv")

df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [2]:
# 필요 컬럼
df = df[[
    "SKU",
    "Price",
    "Stock levels",
    "Order quantities",
    "Lead time",
    "Manufacturing costs"
]]

df.head()

,SKU,Price,Stock levels,Order quantities,Lead time,Manufacturing costs
0,SKU0,69.808006,58,96,29,46.279879
1,SKU1,14.843523,53,37,23,33.616769
2,SKU2,11.319683,1,88,12,30.688019
3,SKU3,61.163343,23,59,24,35.624741
4,SKU4,4.805496,5,56,5,92.065161

In [ ]:
# 기본 QC -> 이상 없음
print("PK/FK 컬럼 중복 확인(SKU):", df["SKU"].nunique(), len(df))
print("원재고 음수 값:", (df["Stock levels"] < 0).sum())

PK/FK 컬럼 중복 확인(SKU): 100 100
원재고 음수 값: 0

In [5]:
# 컬럼명 변경
df = df.rename(columns={
    "SKU" : "material_id",
    "Product type" : "material_type",
    "Price" : "unit_price",
    "Stock levels" : "stock_qty",
    "Order quantities" : "incoming_qty",
    "Lead time" : "lead_time",
    "Manufacturing costs" : "manufacturing_cost"
})

df.head()

,material_id,unit_price,stock_qty,incoming_qty,lead_time,manufacturing_cost
0,SKU0,69.808006,58,96,29,46.279879
1,SKU1,14.843523,53,37,23,33.616769
2,SKU2,11.319683,1,88,12,30.688019
3,SKU3,61.163343,23,59,24,35.624741
4,SKU4,4.805496,5,56,5,92.065161

In [6]:
# PK 타입 정리
df["material_id"] = df["material_id"].astype(str)

In [7]:
# CSV로 내보내기
try:
    df.to_csv("inventory.csv", index=False)
    print("inventory.csv 생성 완료:", df.shape)
    
except Exception as e:
    print("생성 실패:", e)

inventory.csv 생성 완료: (100, 6)